### ISSUE TITLE
POST /api/accounts/sign_in , ** (FunctionClauseError) no function clause matching in RealDealApiWeb.Router.handle_errors/2 

### ISSUE THREAD

**Issue by sanjaykumarsharma** [jacobluetzow/real_deal_api#14]
The log

[info] Access RealDealApiWeb.Endpoint at http://localhost:4000
[info] POST /api/accounts/sign_in
[debug] Processing with RealDealApiWeb.AccountController.sign_in/2
  Parameters: %{"email" => "hime@mainadmin", "hash_password" => "[FILTERED]"}
  Pipelines: [:api]
[debug] QUERY OK source="accounts" db=0.3ms queue=0.5ms idle=1202.0ms
SELECT a0."id", a0."email", a0."hash_password", a0."inserted_at", a0."updated_at" FROM "accounts" AS a0 WHERE (a0."email" = $1) ["hime@mainadmin"]
↳ RealDealApiWeb.Auth.Guardian.authenticate/2, at: lib/real_deal_api_web/auth/guardian.ex:26
[error] #PID<0.522.0> running RealDealApiWeb.Endpoint (connection #PID<0.521.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: POST /api/accounts/sign_in
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in RealDealApiWeb.Router.handle_errors/2
        (real_deal_api 0.1.0) lib/real_deal_api_web/router.ex:5: RealDealApiWeb.Router.handle_errors(%Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{}, body_params: %{"email" => "hime@mainadmin", "hash_password" => "newhiaa@@2202"}, cookies: %{}, halted: false, host: "localhost", method: "POST", owner: #PID<0.522.0>, params: %{"email" => "hime@mainadmin", "hash_password" => "newhiaa@@2202"}, path_info: ["api", "accounts", "sign_in"], path_params: %{}, port: 4000, private: %{RealDealApiWeb.Router => {[], %{}}, :before_send => [#Function<0.77458138/1 in Plug.Session.before_send/2>, #Function<0.23023616/1 in Plug.Telemetry.call/2>], :phoenix_action => :sign_in, :phoenix_controller => RealDealApiWeb.AccountController, :phoenix_endpoint => RealDealApiWeb.Endpoint, :phoenix_format => "json", :phoenix_layout => {RealDealApiWeb.LayoutView, :app}, :phoenix_router => RealDealApiWeb.Router, :phoenix_view => RealDealApiWeb.AccountView, :plug_multipart => :done, :plug_session => %{}, :plug_session_fetch => :done}, query_params: %{}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %{}, req_headers: [{"accept", "*/*"}, {"accept-encoding", "gzip, deflate, br"}, {"connection", "keep-alive"}, {"content-length", "302"}, {"content-type", "multipart/form-data; boundary=--------------------------784123485084835866339270"}, {"host", "localhost:4000"}, {"postman-token", "81a498e4-91a4-46c2-ae42-1f547b55779f"}, {"user-agent", "PostmanRuntime/7.31.0"}], request_path: "/api/accounts/sign_in", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "F0W6_edCRR3l1QQAAAQh"}], scheme: :http, script_name: [], secret_key_base: :..., state: :unset, status: 500}, %{kind: :error, reason: %CaseClauseError{term: {:error, :unauthored}}, stack: [{RealDealApiWeb.AccountController, :authorize_account, 3, [file: 'lib/real_deal_api_web/controllers/account_controller.ex', line: 39]}, {RealDealApiWeb.AccountController, :action, 2, [file: 'lib/real_deal_api_web/controllers/account_controller.ex', line: 1]}, {RealDealApiWeb.AccountController, :phoenix_controller_pipeline, 2, [file: 'lib/real_deal_api_web/controllers/account_controller.ex', line: 1]}, {Phoenix.Router, :__call__, 2, [file: 'lib/phoenix/router.ex', line: 354]}, {RealDealApiWeb.Router, :call, 2, [file: 'lib/plug/error_handler.ex', line: 80]}, {RealDealApiWeb.Endpoint, :plug_builder_call, 2, [file: 'lib/real_deal_api_web/endpoint.ex', line: 1]}, {RealDealApiWeb.Endpoint, :"call (overridable 3)", 2, [file: 'lib/plug/debugger.ex', line: 136]}, {RealDealApiWeb.Endpoint, :call, 2, [file: 'lib/real_deal_api_web/endpoint.ex', line: 1]}, {Phoenix.Endpoint.Cowboy2Handler, :init, 4, [file: 'lib/phoenix/endpoint/cowboy2_handler.ex', line: 54]}, {:cowboy_handler, :execute, 2, [file: '/home/sanjay/projects/real_deal_api/deps/cowboy/src/cowboy_handler.erl', line: 37]}, {:cowboy_stream_h, :execute, 3, [file: '/home/sanjay/projects/real_deal_api/deps/cowboy/src/cowboy_stream_h.erl', line: 306]}, {:cowboy_stream_h, :request_process, 3, [file: '/home/sanjay/projects/real_deal_api/deps/cowboy/src/cowboy_stream_h.erl', line: 295]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]})
        (plug 1.14.0) lib/plug/error_handler.ex:113: Plug.ErrorHandler.__catch__/6
        (real_deal_api 0.1.0) lib/real_deal_api_web/endpoint.ex:1: RealDealApiWeb.Endpoint.plug_builder_call/2
        (real_deal_api 0.1.0) lib/plug/debugger.ex:136: RealDealApiWeb.Endpoint."call (overridable 3)"/2
        (real_deal_api 0.1.0) lib/real_deal_api_web/endpoint.ex:1: RealDealApiWeb.Endpoint.call/2
        (phoenix 1.6.15) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /home/sanjay/projects/real_deal_api/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /home/sanjay/projects/real_deal_api/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /home/sanjay/projects/real_deal_api/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

**Comment by sanjaykumarsharma** [comment]
**Below lines in router is creating issue if there is an unauthorized access.**

def handle_errors(conn, %{reason: %Phoenix.Router.NoRouteError{message: message}}) do
    conn |> json(%{errors: message}) |> halt()
  end

  def handle_errors(conn, %{reason: %{message: message}}) do
    conn |> json(%{errors: message}) |> halt()
  end

**Comment by jacobluetzow** [comment]
Some duplicate files got created, but they have been removed from the project.  That could have been the issue.  Delete the repo and clone it again.
